// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frlqxhawctpbkghmpxbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZybHF4aGF3Y3RwYmtnaG1weGJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjgxODgsImV4cCI6MjA3MzI0NDE4OH0.1OCE1IBkhVrKLLGC_UO9yl_C94C2d11gbLYrUF79OpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});